(defun lightning-dev ()
  (flet ((emacsclient-eval (command)
           (funcall (intern "SHELL-COMMAND" :trivial-shell) (format nil "emacsclient --eval \"~a\"" command))))
    ;; thanks http://turtleware.eu/posts/cl-charms-crash-course.html
    (defvar *console-io* *terminal-io*)
    ;;(push #p"~/other-code/sly/slynk/" asdf:*central-registry*)
    ;;(asdf:load-system :slynk)
    (asdf:load-system :swank)
    (funcall (intern "CREATE-SERVER" :swank) :port 4005 :dont-close t)
    (funcall (intern "QUICKLOAD" :ql) '(:lightning :trivial-shell) :silent t)
    (emacsclient-eval (format nil "(find-file \\\"~a\\\")" (namestring (asdf:system-relative-pathname :lightning "src/lightning.lisp"))))
    (emacsclient-eval "(slime-connect \\\"localhost\\\" 4005)")
    (sleep .5)
    (emacsclient-eval "(funcall 'slime-repl-eval-string \\\"(in-package :lightning)\\\")")
    (sleep .5)
    (emacsclient-eval "(funcall 'slime-repl-eval-string \\\"(fresh-start nil t)\\\")")
    (loop (sleep 1))))

(lightning-dev)
